### ISSUE TITLE
Login doesn't always return a token

### ISSUE THREAD

**Issue by kapadia** [mapbox/usgs#18]
Don't assume [valid XML is returned](https://github.com/mapbox/usgs/blob/96e3e2c47f4be7271a6580109d4c83981154b6b5/usgs/api.py#L149).

    Traceback (most recent call last):
      File "l8_process_run.py", line 178, in <module>
        status = main(sys.argv[1:])
      File "l8_process_run.py", line 155, in main
        limit=args.limit)
      File "l8_process_run.py", line 21, in query_for_scenes
        os.environ['USGS_PASSWORD'])
      File "usgs/api.py", line 149, in login
        root = ElementTree.fromstring(r.text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
        self._raiseerror(v)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
        raise err
    xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 337

/cc @warmerdam

**Comment by kapadia** [comment]
Logins failing due to mal-formed XML now raise an error, and will output the response from USGS servers. This response should be used to debug projects like [landsat-ingestor](https://github.com/landsat-pds/landsat_ingestor/blob/f34d8d12814515f126bf481ce3e22e482d53a8f3/ingestor/l8_process_run.py#L20-L21).
